# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: usart.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='usart.proto',
  package='cpre288',
  serialized_pb=_b('\n\x0busart.proto\x12\x07\x63pre288\"!\n\ndepth_data\x12\x13\n\x0b\x64\x65pth_array\x18\x03 \x03(\r\"\x16\n\x05\x64\x65pth\x12\r\n\x05\x64\x65pth\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_DEPTH_DATA = _descriptor.Descriptor(
  name='depth_data',
  full_name='cpre288.depth_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depth_array', full_name='cpre288.depth_data.depth_array', index=0,
      number=3, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=57,
)


_DEPTH = _descriptor.Descriptor(
  name='depth',
  full_name='cpre288.depth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='depth', full_name='cpre288.depth.depth', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['depth_data'] = _DEPTH_DATA
DESCRIPTOR.message_types_by_name['depth'] = _DEPTH

depth_data = _reflection.GeneratedProtocolMessageType('depth_data', (_message.Message,), dict(
  DESCRIPTOR = _DEPTH_DATA,
  __module__ = 'usart_pb2'
  # @@protoc_insertion_point(class_scope:cpre288.depth_data)
  ))
_sym_db.RegisterMessage(depth_data)

depth = _reflection.GeneratedProtocolMessageType('depth', (_message.Message,), dict(
  DESCRIPTOR = _DEPTH,
  __module__ = 'usart_pb2'
  # @@protoc_insertion_point(class_scope:cpre288.depth)
  ))
_sym_db.RegisterMessage(depth)


# @@protoc_insertion_point(module_scope)
